from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
VERSIONS_DIR = REPO_ROOT / "alembic" / "versions"
FORBIDDEN_MARKER = "auto generated by Alembic"


def migration_files() -> list[Path]:
    return sorted(VERSIONS_DIR.glob("*.py"))


def files_with_autogenerate_marker() -> list[Path]:
    return [
        path
        for path in migration_files()
        if FORBIDDEN_MARKER in path.read_text(encoding="utf-8")
    ]


def test_migrations_do_not_contain_alembic_autogenerate_comments() -> None:
    offenders = files_with_autogenerate_marker()

    assert offenders == [], "Forbidden Alembic autogenerate comments: " + ", ".join(
        path.as_posix() for path in offenders
    )


def test_autogenerate_guard_detects_temporary_bad_migration() -> None:
    temp_path = VERSIONS_DIR / "99999999_999999_autogenerate_guard_fixture.py"
    temp_path.write_text(f"# {FORBIDDEN_MARKER}\n", encoding="utf-8")

    try:
        assert temp_path in files_with_autogenerate_marker()
    finally:
        temp_path.unlink(missing_ok=True)

    assert temp_path not in files_with_autogenerate_marker()
