from __future__ import annotations

import importlib.util
from pathlib import Path
from types import ModuleType

import sqlalchemy as sa

REPO_ROOT = Path(__file__).resolve().parents[2]
VERSIONS_DIR = REPO_ROOT / "alembic" / "versions"
FORBIDDEN_MARKER = "auto generated by Alembic"
REVOCATION_MIGRATION = (
    VERSIONS_DIR / "20260731_090000_credential_revocation.py"
)


class MigrationOperationsRecorder:
    def __init__(self) -> None:
        self.calls: list[tuple[str, tuple[object, ...], dict[str, object]]] = []

    def add_column(self, *args: object, **kwargs: object) -> None:
        self.calls.append(("add_column", args, kwargs))

    def drop_column(self, *args: object, **kwargs: object) -> None:
        self.calls.append(("drop_column", args, kwargs))


def migration_files() -> list[Path]:
    return sorted(VERSIONS_DIR.glob("*.py"))


def files_with_autogenerate_marker() -> list[Path]:
    return [
        path
        for path in migration_files()
        if FORBIDDEN_MARKER in path.read_text(encoding="utf-8")
    ]


def load_revocation_migration() -> ModuleType:
    spec = importlib.util.spec_from_file_location(
        "credential_revocation_migration",
        REVOCATION_MIGRATION,
    )
    if spec is None or spec.loader is None:
        raise AssertionError("revocation migration must be importable")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_migrations_do_not_contain_alembic_autogenerate_comments() -> None:
    offenders = files_with_autogenerate_marker()

    assert offenders == [], "Forbidden Alembic autogenerate comments: " + ", ".join(
        path.as_posix() for path in offenders
    )


def test_autogenerate_guard_detects_temporary_bad_migration() -> None:
    temp_path = VERSIONS_DIR / "99999999_999999_autogenerate_guard_fixture.py"
    temp_path.write_text(f"# {FORBIDDEN_MARKER}\n", encoding="utf-8")

    try:
        assert temp_path in files_with_autogenerate_marker()
    finally:
        temp_path.unlink(missing_ok=True)

    assert temp_path not in files_with_autogenerate_marker()


def test_revocation_migration_upgrade_only_adds_nullable_timestamptz() -> None:
    migration = load_revocation_migration()
    recorder = MigrationOperationsRecorder()
    migration.op = recorder

    migration.upgrade()

    assert migration.revision == "20260731_090000"
    assert migration.down_revision == "20260724_090000"
    assert len(recorder.calls) == 1
    operation, args, kwargs = recorder.calls[0]
    assert operation == "add_column"
    assert kwargs == {}
    assert len(args) == 2
    assert args[0] == "oa_session_credentials"
    column = args[1]
    assert isinstance(column, sa.Column)
    assert column.name == "revoked_at"
    assert isinstance(column.type, sa.DateTime)
    assert column.type.timezone is True
    assert column.nullable is True
    assert column.default is None
    assert column.server_default is None
    assert column.index is None
    assert column.unique is None
    assert list(column.constraints) == []
    assert list(column.foreign_keys) == []


def test_revocation_migration_downgrade_only_drops_its_column() -> None:
    migration = load_revocation_migration()
    recorder = MigrationOperationsRecorder()
    migration.op = recorder

    migration.downgrade()

    assert recorder.calls == [
        (
            "drop_column",
            ("oa_session_credentials", "revoked_at"),
            {},
        )
    ]
